# Generated by Django 4.2.5 on 2023-09-23 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city_name', models.CharField(max_length=200)),
                ('seller_score', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Trendyol_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('sellingPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discountedPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=200)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrap.merchant')),
                ('other_merchants', models.ManyToManyField(related_name='other_Merchants', to='scrap.merchant')),
            ],
        ),
    ]
