# Generated by Django 4.2.5 on 2023-09-23 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0002_trendyol_product_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchant',
            options={'verbose_name': 'Satıcı', 'verbose_name_plural': 'Satıcılar'},
        ),
        migrations.AlterModelOptions(
            name='trendyol_product',
            options={'verbose_name': 'Ürün', 'verbose_name_plural': 'Ürünler'},
        ),
    ]
